version: 2
project_name: recall
before:
  hooks:
    - go mod tidy
builds:
  - id: recall
    main: .
    binary: recall
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - id: recall
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]
    formats: [tar.gz]
checksum:
  name_template: "checksums.txt"
release:
  github:
    owner: parthsigdel
    name: recall
