version: 2
project_name: recall
before:
  hooks:
    - go mod tidy
builds:
  - id: recall
    main: .
    binary: recall
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - id: recall
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
checksum:
  name_template: "checksums.txt"
release:
  github:
    owner: parthsigdel
    name: recall
